from dash import dcc
from dash import html
from dash import dash_table
import dash_daq as daq
import dash_bootstrap_components as dbc

from assets.storage import CONSISTENCY_DATA

def tab_consistency(consistency_data=CONSISTENCY_DATA):
    consistency_data['Q'] = consistency_data['Q'].round(2)
    consistency_data['p-value'] = consistency_data['p-value'].round(3)
    return html.Div([
        html.Div([
       #      dbc.Col([
       #                       html.P(
       #                       "Outcome 1",
       #                       id='consistencyswitchlabel1',
       #                       style={'display': 'inline-block',
       #                              'margin': 'auto',
       #                              'fontSize': '10px',
       #                              'paddingLeft': '0px'}),
       #                       daq.ToggleSwitch(
       #                           id='toggle_consistency_direction',
       #                           color='', size=30, vertical=False,
       #                           label={'label': "",
       #                                  'style': dict(color='white', font='0.5em')},
       #                           labelPosition="top",
       #                           style={'display': 'inline-block',
       #                                  'margin': 'auto', 'fontSize': '10px',
       #                                  'paddingLeft': '2px',
       #                                  'paddingRight': '2px'}),
       #                       html.P('Outcome 2',
       #                              id='consistencyswitchlabel2',
       #                              style={'display': 'inline-block',
       #                                     'margin': 'auto',
       #                                     'fontSize': '10px',
       #                                     'paddingRight': '0px'})],
       #                       style={'flex-grow': '1', 'justifyContent': 'flex-end',
       #                             'display': 'flex', 'marginLeft': '70%',
       #                             'fontSize': '0.8em', 'marginTop': '2%'},
       #                       ),
       # dbc.Col(
       #  dbc.Row(
       #        [html.P(f"Select outcomes",className="selectbox", style={'display': 'inline-block', "textAlign": 'right',
       #                                                         'marginLeft': '0px', 'fontSize': '12px'}),
       #        dcc.Dropdown(id='consistency_outcome_select', searchable=True, placeholder="...", className="box",
       #                      clearable=False, value=0,
       #                      style={'width': '80px',  # 'height': '30px',
       #                             "height": '30px',
       #                             'verticalAlign': 'middle',
       #                             "fontFamily": "sans-serif",
       #                             'marginBottom': '2px',
       #                             'display': 'inline-block',
       #                             'color': 'black',
       #                             'fontSize': '10px','marginLeft':'-7px'})]),
       #                             style={'marginBottom': '0px', 'justifyContent': 'end', 'display': 'flex'}
       #                             ),
        html.Br(), html.Br(),
        html.P("Design-by-treatment interaction model", style={'fontSize': '12px', 'marginTop': '-0.6%'},
                     className="box__title")]),
        dash_table.DataTable(
        id='consistency-table',
        export_format="csv",
        columns=[{"name": i, "id": i} for i in consistency_data.columns],
        data=consistency_data.to_dict('records'),
        style_cell={'backgroundColor': 'rgba(0,0,0,0.1)',
                'color': 'black',
                'textAlign': 'center',
                'minWidth': '35px',
                'maxWidth': '40px',
                'border': '1px solid #5d6d95',
                'overflow': 'hidden', 'whiteSpace': 'no-wrap',
                'textOverflow': 'ellipsis',
                'fontFamily': 'sans-serif',
                'fontSize': 11},
        style_data_conditional=[
        {'if': {
                'filter_query': '{p-value} > 0 && {p-value} < 0.10',
                'column_id': 'p-value'},
                'color': 'tomato',
                'fontWeight': 'bold'
         },
        {'if': {'row_index': 'odd'},
         'backgroundColor': 'rgba(0,0,0,0.2)'},
        {'if': {'state': 'active'},
         'backgroundColor': 'rgba(0, 116, 217, 0.3)',
         'border': '1px solid rgb(0, 116, 217)'}],
        style_header={'backgroundColor': 'slategrey',
                  'fontWeight': 'bold',
                  'border': '1px solid #5d6d95'},
        style_table={'overflowX': 'scroll',
                 'overflowY': 'scroll',
                 'height': '99%',
                 'max-height': '400px',
                 'minWidth': '100%',
                 'width': '99%',
                 'max-width': 'calc(52vw)',
                 'padding': '5px 5px 5px 5px'},
        css=[
        {'selector': 'tr:hover',
         'rule': 'background-color: rgba(0, 0, 0, 0);'},
        {'selector': 'td:hover',
         'rule': 'background-color: rgba(0, 116, 217, 0.3) !important;'}]
    ),
    html.Br(),
    html.Div([ html.Div([ html.P("Side-splitting model",
                     style={'fontSize': '12px', 'marginTop': '0.8%', 'display': 'inline-block'},
                     className="box__title"),html.Br(),
              html.P("Select edge(s) to display specific comparison(s)",
                     style={'fontSize': '12px', 'marginTop': '-1.2%', 'display': 'inline-block'},
                     className="box__title") ]),
              html.Div([html.Button('Export', id='consistency-export', n_clicks=0, className="btn-export2",
                                    style={'marginRight': '31%', 'padding': '4px 4px 4px 4px',
                                           'color': 'black', 'fontSize': 10, 'marginTop': '-7%',
                                           'fontWeight': '900', 'fontFamily': 'sans-serif', 'display': 'inline-block',
                                           }),
                        html.P(id='export-cons-button-hidden', style={'display': 'none'}),
                        dcc.Download(id="download_consistency")]),
              html.Div([html.Button('Save all', 'btn-netsplit-all', n_clicks=0,className="btn-export2",
                          style={'padding': '0px 4px 0px 4px','marginRight': '20%',
                                 'marginBottom': '2px', 'fontSize': 10,'marginTop': '-7%',
                                 'fontWeight': '900', 'fontFamily': 'sans-serif', 'display': 'inline-block',
                                 }),
                        html.P(id='export-cons-all-button-hidden', style={'display': 'none'}),
                        dcc.Download(id="download_consistency_all"),
                        dbc.Tooltip("All net-split results with indirect comparisons",
                                    style={'color': 'black', 'fontSize': 9,
                                           'marginLeft': '10px',
                                           'letterSpacing': '0.3rem'},
                                    placement='top',
                                    target='btn-netsplit-all'),
                        ]),
              html.Div(dash_table.DataTable(
            id='netsplit_table-container',
            fixed_rows={'headers': True, 'data': 0},
            #export_format="csv", #xlsx
            #columns=[{"name": i, "id": i} for i in df.columns],
            #data=df.to_dict('records'),
            style_cell={'backgroundColor': 'rgba(0,0,0,0)',
                'color': 'black',
                'textAlign': 'center',
                'minWidth': '35px',
                'maxWidth': '40px',
                'border': '1px solid #5d6d95',
                'overflow': 'hidden', 'whiteSpace': 'no-wrap',
                'textOverflow': 'ellipsis',
                'fontFamily': 'sans-serif',
                'fontSize': 11},
             style_data_conditional=[
            {'if': {'filter_query': '{p-value} <= 0.05',
                'column_id': 'p-value'},
            'color': 'tomato',
            'fontWeight': 'bold'
            },
            {'if': {'filter_query': '{p-value} > 0.05 && {p-value} <= 0.10',
            'column_id': 'p-value'},
             'color': '#f2940',
             'fontWeight': 'bold'
             },
             {'if': {'filter_query': '{p-value} > 0.10 && {p-value} <= 0.15',
                         'column_id': 'p-value'},
                  'color': 'blue',
                  'fontWeight': 'bold'
             },
            {'if': {'row_index': 'odd'},
            'backgroundColor': 'rgba(0,0,0,0.1)'},
            {'if': {'state': 'active'},
            'backgroundColor': 'rgba(0, 116, 217, 0.3)',
            'border': '1px solid rgb(0, 116, 217)'}],
            style_header={'backgroundColor': 'grey',
                  'fontWeight': 'bold',
                  'border': '1px solid #5d6d95'},
            style_table={'overflowX': 'scroll',
                 'overflowY': 'scroll',
                 'height': '97%',
                 'max-height': 'calc(30vh)',
                 'minWidth': '100%',
                 'width': '90%',
                 'max-width': 'calc(50vw)',
                 'padding': '5px 5px 5px 5px'},
            css=[
            {'selector': 'tr:hover',
            'rule': 'background-color: rgba(0, 0, 0, 0);'},
            {'selector': 'td:hover',
             'rule': 'background-color: rgba(0, 116, 217, 0.3) !important;'}])),
              ]),
    html.Br(),
    ])
